PROCESS BEFORE OUTPUT.
* MODULE STATUS_0132.

  MODULE POPULATE_SM12_0132.
  LOOP AT it_lockdetails INTO wa_lockdetail WITH CONTROL  ZSM12TAB.

    MODULE zsm12mapping.

  ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE USER_COMMAND_0132.

  LOOP .
  ENDLOOP.
