PROCESS BEFORE OUTPUT.
* MODULE STATUS_0136.
*

  CALL SUBSCREEN st22ss INCLUDING sy-repid '0137'.

PROCESS AFTER INPUT.
  CALL SUBSCREEN st22ss.
  MODULE user_command_0136.
  MODULE zexit AT EXIT-COMMAND.
