PROCESS BEFORE OUTPUT.

*  MODULE populate_initial_0130.

  CALL SUBSCREEN SS2 INCLUDING SY-REPID '0131'.

*  MODULE status_0130.
*
PROCESS AFTER INPUT.
  CALL SUBSCREEN SS2.
  MODULE user_command_0130.
  MODULE zexit AT EXIT-COMMAND.
