PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZEMP_M_VIEW CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZEMP_M_VIEW-EID .
    FIELD ZEMP_M_VIEW-ENAME .
    FIELD ZEMP_M_VIEW-EAGE .
    FIELD ZEMP_M_VIEW-EROLE .
    FIELD ZEMP_M_VIEW-EPHONE .
    FIELD ZEMP_M_VIEW-EADDR .
    FIELD ZEMP_M_VIEW-ECONT .
    FIELD ZEMP_M_VIEW-MANDT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZEMP_M_VIEW-EID .
    FIELD ZEMP_M_VIEW-MANDT .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
