PROCESS BEFORE OUTPUT.
 CALL SUBSCREEN SS1 INCLUDING SY-REPID LV_SCREEN.
 MODULE STATUS_0120.
*
PROCESS AFTER INPUT.
 MODULE USER_COMMAND_0120.
 MODULE EXIT_COMMAND_0120 AT EXIT-COMMAND.

PROCESS ON HELP-REQUEST.
   FIELD IOEID MODULE EIDHELP.
