*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZEMP_M_VIEW.....................................*
FORM GET_DATA_ZEMP_M_VIEW.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZEMPLOYEE WHERE
(VIM_WHERETAB) .
    CLEAR ZEMP_M_VIEW .
ZEMP_M_VIEW-EID =
ZEMPLOYEE-EID .
ZEMP_M_VIEW-ENAME =
ZEMPLOYEE-ENAME .
ZEMP_M_VIEW-EAGE =
ZEMPLOYEE-EAGE .
ZEMP_M_VIEW-EROLE =
ZEMPLOYEE-EROLE .
    SELECT SINGLE * FROM ZEMPLOYEEADDR WHERE
EID = ZEMPLOYEE-EID .
    IF SY-SUBRC EQ 0.
ZEMP_M_VIEW-EPHONE =
ZEMPLOYEEADDR-EPHONE .
ZEMP_M_VIEW-EADDR =
ZEMPLOYEEADDR-EADDR .
ZEMP_M_VIEW-ECONT =
ZEMPLOYEEADDR-ECONT .
ZEMP_M_VIEW-MANDT =
ZEMPLOYEEADDR-MANDT .
    ENDIF.
<VIM_TOTAL_STRUC> = ZEMP_M_VIEW.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZEMP_M_VIEW .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZEMP_M_VIEW.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZEMP_M_VIEW-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZEMPLOYEE WHERE
  EID = ZEMP_M_VIEW-EID .
    IF SY-SUBRC = 0.
    DELETE ZEMPLOYEE .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM ZEMPLOYEEADDR WHERE
    EID = ZEMPLOYEE-EID .
    IF SY-SUBRC = 0.
    DELETE ZEMPLOYEEADDR .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZEMPLOYEE WHERE
  EID = ZEMP_M_VIEW-EID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZEMPLOYEE.
    ENDIF.
ZEMPLOYEE-EID =
ZEMP_M_VIEW-EID .
ZEMPLOYEE-ENAME =
ZEMP_M_VIEW-ENAME .
ZEMPLOYEE-EAGE =
ZEMP_M_VIEW-EAGE .
ZEMPLOYEE-EROLE =
ZEMP_M_VIEW-EROLE .
    IF SY-SUBRC = 0.
    UPDATE ZEMPLOYEE ##WARN_OK.
    ELSE.
    INSERT ZEMPLOYEE .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM ZEMPLOYEEADDR WHERE
    EID = ZEMPLOYEE-EID .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR ZEMPLOYEEADDR.
ZEMPLOYEEADDR-EID =
ZEMPLOYEE-EID .
      ENDIF.
ZEMPLOYEEADDR-EPHONE =
ZEMP_M_VIEW-EPHONE .
ZEMPLOYEEADDR-EADDR =
ZEMP_M_VIEW-EADDR .
ZEMPLOYEEADDR-ECONT =
ZEMP_M_VIEW-ECONT .
ZEMPLOYEEADDR-MANDT =
ZEMP_M_VIEW-MANDT .
    IF SY-SUBRC = 0.
    UPDATE ZEMPLOYEEADDR ##WARN_OK.
    ELSE.
    INSERT ZEMPLOYEEADDR .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZEMP_M_VIEW-UPD_FLAG,
STATUS_ZEMP_M_VIEW-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZEMP_M_VIEW.
  SELECT SINGLE * FROM ZEMPLOYEE WHERE
EID = ZEMP_M_VIEW-EID .
ZEMP_M_VIEW-EID =
ZEMPLOYEE-EID .
ZEMP_M_VIEW-ENAME =
ZEMPLOYEE-ENAME .
ZEMP_M_VIEW-EAGE =
ZEMPLOYEE-EAGE .
ZEMP_M_VIEW-EROLE =
ZEMPLOYEE-EROLE .
    SELECT SINGLE * FROM ZEMPLOYEEADDR WHERE
EID = ZEMPLOYEE-EID .
    IF SY-SUBRC EQ 0.
ZEMP_M_VIEW-EPHONE =
ZEMPLOYEEADDR-EPHONE .
ZEMP_M_VIEW-EADDR =
ZEMPLOYEEADDR-EADDR .
ZEMP_M_VIEW-ECONT =
ZEMPLOYEEADDR-ECONT .
ZEMP_M_VIEW-MANDT =
ZEMPLOYEEADDR-MANDT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZEMP_M_VIEW-EPHONE .
      CLEAR ZEMP_M_VIEW-EADDR .
      CLEAR ZEMP_M_VIEW-ECONT .
      CLEAR ZEMP_M_VIEW-MANDT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZEMP_M_VIEW USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZEMP_M_VIEW-EID TO
ZEMPLOYEE-EID .
MOVE SY-MANDT TO
ZEMPLOYEE-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZEMPLOYEE'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZEMPLOYEE TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZEMPLOYEE'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE ZEMPLOYEE-EID TO
ZEMPLOYEEADDR-EID .
MOVE SY-MANDT TO
ZEMPLOYEEADDR-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZEMPLOYEEADDR'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZEMPLOYEEADDR TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZEMPLOYEEADDR'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*

* base table related FORM-routines.............
INCLUDE LSVIMFTX .
