PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZEMPLOYEE CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZEMPLOYEE-EID .
    FIELD ZEMPLOYEE-ENAME .
    FIELD ZEMPLOYEE-EAGE .
    FIELD ZEMPLOYEE-EROLE .
    FIELD ZEMPLOYEE-CREATED_ON .
    FIELD ZEMPLOYEE-CREATED_BY .
    FIELD ZEMPLOYEE-CREATED_AT .
    FIELD ZEMPLOYEE-LAST_CHANED_BY .
    FIELD ZEMPLOYEE-LAST_CHANED_ON .
    FIELD ZEMPLOYEE-LAST_CHAGED_AT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZEMPLOYEE-EID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
